version: '3.2'

services:
  db:
    container_name: MYSQL
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'task-manager'
      MYSQL_PASSWORD: '3042'
      MYSQL_ROOT_PASSWORD: '3042'
    expose:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql

  zookeeper:
    container_name: ZOOKEEPER
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    container_name: KAFKA
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
